#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../dist

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

if [ "${ARCH}" != "amd64" ]; then
    tar cvzf share-mnt-${ARCH}.tar.gz -C ../bin share-mnt
else
    tar cvzf share-mnt.tar.gz -C ../bin share-mnt
fi

echo Created share-mnt.tar.gz
